name: Backend
on: push

defaults:
  run:
    working-directory: backend
jobs:
  build:
    name: Run Python Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup timezone
        uses: zcong1993/setup-timezone@master
        with:
          timezone: UTC

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
          cache: 'pip' # caching pip dependencies

      - name: Install Python dependencies
        run: |
          sudo apt install -y $(grep -o ^[^#][[:alnum:]-]* "packages.list")
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt

      - name: Test with pytest
        run: |
          pytest --exitfirst --verbose --failed-first \
          --cov=. --cov-report html
